require "trailblazer/activity/dsl"
require "trailblazer/core"

require "minitest/autorun"

CU = Trailblazer::Core::Utils
T = Trailblazer::Core

class Minitest::Spec
  include Trailblazer::Core::Utils::AssertEqual
  include Trailblazer::Core::Utils::AssertRun
end

# require "trailblazer/developer"

# Trailblazer::Core.convert_operation_test("test/docs/sequence_options_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/sequence_options_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/mechanics_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/mechanics_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/wiring_api_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/wiring_api_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/subprocess_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/subprocess_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/fast_track_layout_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/fast_track_layout_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/activity_basics_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/activity_basics_test.rb", source_gem: "trailblazer-activity-dsl-linear")
# Trailblazer::Core.convert_operation_test("test/docs/composable_variable_mapping_test.rb", target: "../trailblazer-operation/test/docs/autogenerated/composable_variable_mapping_test.rb", source_gem: "trailblazer-activity-dsl-linear")
