require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"] - FileList["test/docs/autogenerated/*"] -
    FileList["test/docs/variable_mapping_test.rb"] # we don't want :input tests anymore, but need them for documentation.
end

task :default => :test
