require "test_helper"
module Autogenerated
module X
  class DocsActivityTest < Minitest::Spec
    it "basic activity" do
      Memo = Class.new

      #:memo-create
      module Memo::Operation
        class Create < Trailblazer::Operation
          step :validate
          #~body
          step :save
          left :handle_errors
          step :notify
          #~meths
          include T.def_steps(:validate, :save, :handle_errors, :notify)

          def save(ctx, **)
            true
          end

          def notify(ctx, **)
            true
          end

          #~body end
          def validate(ctx, params:, **) # home-made validation
            params.key?(:memo) &&
            params[:memo].key?(:text) &&
            params[:memo][:text].size > 9
            # return value matters!
          end
          #~meths end
        end
      end
      #:memo-create end

      #:memo-call
      result = Memo::Operation::Create.(
        params: {memo: {text: "Do not forget!"}}
      )

      result.success? # => true
      puts signal.to_h[:semantic] #=> :success
      #:memo-call end

      assert_equal result.event.inspect, %(#<Trailblazer::Operation::End semantic=:success>)

      assert_invoke Memo::Operation::Create, seq: "[]", params: {memo: {text: "do not forget!"}}
      assert_invoke Memo::Operation::Create, seq: "[:handle_errors]", params: {}, terminus: :failure
    end
  end
end
end