require "test_helper"
module Autogenerated
module X
  class DocsActivityTest < Minitest::Spec
    it "basic activity" do
      Memo = Struct.new(:options) do
        def save
          true
        end
      end

      #:memo-create
      module Memo::Operation
        class Create < Trailblazer::Operation
          step :validate
          #~body
          step :save
          left :handle_errors
          step :notify
          #~meths
          include T.def_steps(:validate, :save, :handle_errors, :notify)

          #:save
          def save(ctx, params:, **)
            memo = Memo.new(params[:memo])
            memo.save

            ctx[:model] = memo # you can write to the {ctx}.
          end
          #:save end

          def notify(ctx, **)
            true
          end

          #~body end
          def validate(ctx, params:, **) # home-made validation
            params.key?(:memo) &&
            params[:memo].key?(:text) &&
            params[:memo][:text].size > 9
            # return value matters!
          end
          #~meths end
        end
      end
      #:memo-create end

      #:memo-call
      result = Memo::Operation::Create.(
        params: {memo: {text: "Do not forget!"}}
      )

      result.success? # => true
      puts signal.to_h[:semantic] #=> :success
      #:memo-call end

      #:memo-call-model
      result = Memo::Operation::Create.(
        params: {memo: {text: "Do not forget!"}}
      )

      #~ctx_to_result
      puts result[:model] #=> #<Memo id: 1 text: "Do not forget!">
      #:memo-call-model end
      #~ctx_to_result end

      assert_equal result.event.inspect, %(#<Trailblazer::Operation::End semantic=:success>)
      assert_equal result.inspect, %({:params=>{:memo=>{:text=>\"Do not forget!\"}}, :model=>#<struct X::DocsActivityTest::Memo options={:text=>\"Do not forget!\"}>})

      model = ctx[:model]

      assert_invoke Memo::Operation::Create, seq: "[]", params: {memo: {text: "Do not forget!"}}, expected_ctx_variables: {model: model}
      assert_invoke Memo::Operation::Create, seq: "[:handle_errors]", params: {}, terminus: :failure
    end
  end
end
end